version: '2'

services:
    nginx:
        restart: unless-stopped
        build:
            context: .
            dockerfile: ./docker/nginx/Dockerfile
        ports:
            - 85:85
        volumes:
            - ./docker/nginx/development.conf:/etc/nginx/conf.d/default.conf:ro
